// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ai-gallery/ent/baseschema"
	"ai-gallery/ent/predicate"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BaseSchemaQuery is the builder for querying BaseSchema entities.
type BaseSchemaQuery struct {
	config
	ctx        *QueryContext
	order      []baseschema.OrderOption
	inters     []Interceptor
	predicates []predicate.BaseSchema
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BaseSchemaQuery builder.
func (bsq *BaseSchemaQuery) Where(ps ...predicate.BaseSchema) *BaseSchemaQuery {
	bsq.predicates = append(bsq.predicates, ps...)
	return bsq
}

// Limit the number of records to be returned by this query.
func (bsq *BaseSchemaQuery) Limit(limit int) *BaseSchemaQuery {
	bsq.ctx.Limit = &limit
	return bsq
}

// Offset to start from.
func (bsq *BaseSchemaQuery) Offset(offset int) *BaseSchemaQuery {
	bsq.ctx.Offset = &offset
	return bsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (bsq *BaseSchemaQuery) Unique(unique bool) *BaseSchemaQuery {
	bsq.ctx.Unique = &unique
	return bsq
}

// Order specifies how the records should be ordered.
func (bsq *BaseSchemaQuery) Order(o ...baseschema.OrderOption) *BaseSchemaQuery {
	bsq.order = append(bsq.order, o...)
	return bsq
}

// First returns the first BaseSchema entity from the query.
// Returns a *NotFoundError when no BaseSchema was found.
func (bsq *BaseSchemaQuery) First(ctx context.Context) (*BaseSchema, error) {
	nodes, err := bsq.Limit(1).All(setContextOp(ctx, bsq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{baseschema.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (bsq *BaseSchemaQuery) FirstX(ctx context.Context) *BaseSchema {
	node, err := bsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BaseSchema ID from the query.
// Returns a *NotFoundError when no BaseSchema ID was found.
func (bsq *BaseSchemaQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bsq.Limit(1).IDs(setContextOp(ctx, bsq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{baseschema.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (bsq *BaseSchemaQuery) FirstIDX(ctx context.Context) int {
	id, err := bsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BaseSchema entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BaseSchema entity is found.
// Returns a *NotFoundError when no BaseSchema entities are found.
func (bsq *BaseSchemaQuery) Only(ctx context.Context) (*BaseSchema, error) {
	nodes, err := bsq.Limit(2).All(setContextOp(ctx, bsq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{baseschema.Label}
	default:
		return nil, &NotSingularError{baseschema.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (bsq *BaseSchemaQuery) OnlyX(ctx context.Context) *BaseSchema {
	node, err := bsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BaseSchema ID in the query.
// Returns a *NotSingularError when more than one BaseSchema ID is found.
// Returns a *NotFoundError when no entities are found.
func (bsq *BaseSchemaQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bsq.Limit(2).IDs(setContextOp(ctx, bsq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{baseschema.Label}
	default:
		err = &NotSingularError{baseschema.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (bsq *BaseSchemaQuery) OnlyIDX(ctx context.Context) int {
	id, err := bsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BaseSchemas.
func (bsq *BaseSchemaQuery) All(ctx context.Context) ([]*BaseSchema, error) {
	ctx = setContextOp(ctx, bsq.ctx, "All")
	if err := bsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BaseSchema, *BaseSchemaQuery]()
	return withInterceptors[[]*BaseSchema](ctx, bsq, qr, bsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (bsq *BaseSchemaQuery) AllX(ctx context.Context) []*BaseSchema {
	nodes, err := bsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BaseSchema IDs.
func (bsq *BaseSchemaQuery) IDs(ctx context.Context) (ids []int, err error) {
	if bsq.ctx.Unique == nil && bsq.path != nil {
		bsq.Unique(true)
	}
	ctx = setContextOp(ctx, bsq.ctx, "IDs")
	if err = bsq.Select(baseschema.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (bsq *BaseSchemaQuery) IDsX(ctx context.Context) []int {
	ids, err := bsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (bsq *BaseSchemaQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, bsq.ctx, "Count")
	if err := bsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, bsq, querierCount[*BaseSchemaQuery](), bsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (bsq *BaseSchemaQuery) CountX(ctx context.Context) int {
	count, err := bsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (bsq *BaseSchemaQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, bsq.ctx, "Exist")
	switch _, err := bsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (bsq *BaseSchemaQuery) ExistX(ctx context.Context) bool {
	exist, err := bsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BaseSchemaQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (bsq *BaseSchemaQuery) Clone() *BaseSchemaQuery {
	if bsq == nil {
		return nil
	}
	return &BaseSchemaQuery{
		config:     bsq.config,
		ctx:        bsq.ctx.Clone(),
		order:      append([]baseschema.OrderOption{}, bsq.order...),
		inters:     append([]Interceptor{}, bsq.inters...),
		predicates: append([]predicate.BaseSchema{}, bsq.predicates...),
		// clone intermediate query.
		sql:  bsq.sql.Clone(),
		path: bsq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BaseSchema.Query().
//		GroupBy(baseschema.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (bsq *BaseSchemaQuery) GroupBy(field string, fields ...string) *BaseSchemaGroupBy {
	bsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BaseSchemaGroupBy{build: bsq}
	grbuild.flds = &bsq.ctx.Fields
	grbuild.label = baseschema.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.BaseSchema.Query().
//		Select(baseschema.FieldCreateTime).
//		Scan(ctx, &v)
func (bsq *BaseSchemaQuery) Select(fields ...string) *BaseSchemaSelect {
	bsq.ctx.Fields = append(bsq.ctx.Fields, fields...)
	sbuild := &BaseSchemaSelect{BaseSchemaQuery: bsq}
	sbuild.label = baseschema.Label
	sbuild.flds, sbuild.scan = &bsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BaseSchemaSelect configured with the given aggregations.
func (bsq *BaseSchemaQuery) Aggregate(fns ...AggregateFunc) *BaseSchemaSelect {
	return bsq.Select().Aggregate(fns...)
}

func (bsq *BaseSchemaQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range bsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, bsq); err != nil {
				return err
			}
		}
	}
	for _, f := range bsq.ctx.Fields {
		if !baseschema.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if bsq.path != nil {
		prev, err := bsq.path(ctx)
		if err != nil {
			return err
		}
		bsq.sql = prev
	}
	return nil
}

func (bsq *BaseSchemaQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BaseSchema, error) {
	var (
		nodes = []*BaseSchema{}
		_spec = bsq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BaseSchema).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BaseSchema{config: bsq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, bsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (bsq *BaseSchemaQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := bsq.querySpec()
	_spec.Node.Columns = bsq.ctx.Fields
	if len(bsq.ctx.Fields) > 0 {
		_spec.Unique = bsq.ctx.Unique != nil && *bsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, bsq.driver, _spec)
}

func (bsq *BaseSchemaQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(baseschema.Table, baseschema.Columns, sqlgraph.NewFieldSpec(baseschema.FieldID, field.TypeInt))
	_spec.From = bsq.sql
	if unique := bsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if bsq.path != nil {
		_spec.Unique = true
	}
	if fields := bsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, baseschema.FieldID)
		for i := range fields {
			if fields[i] != baseschema.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := bsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := bsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := bsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := bsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (bsq *BaseSchemaQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(bsq.driver.Dialect())
	t1 := builder.Table(baseschema.Table)
	columns := bsq.ctx.Fields
	if len(columns) == 0 {
		columns = baseschema.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if bsq.sql != nil {
		selector = bsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if bsq.ctx.Unique != nil && *bsq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range bsq.predicates {
		p(selector)
	}
	for _, p := range bsq.order {
		p(selector)
	}
	if offset := bsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := bsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BaseSchemaGroupBy is the group-by builder for BaseSchema entities.
type BaseSchemaGroupBy struct {
	selector
	build *BaseSchemaQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bsgb *BaseSchemaGroupBy) Aggregate(fns ...AggregateFunc) *BaseSchemaGroupBy {
	bsgb.fns = append(bsgb.fns, fns...)
	return bsgb
}

// Scan applies the selector query and scans the result into the given value.
func (bsgb *BaseSchemaGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bsgb.build.ctx, "GroupBy")
	if err := bsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BaseSchemaQuery, *BaseSchemaGroupBy](ctx, bsgb.build, bsgb, bsgb.build.inters, v)
}

func (bsgb *BaseSchemaGroupBy) sqlScan(ctx context.Context, root *BaseSchemaQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(bsgb.fns))
	for _, fn := range bsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*bsgb.flds)+len(bsgb.fns))
		for _, f := range *bsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*bsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BaseSchemaSelect is the builder for selecting fields of BaseSchema entities.
type BaseSchemaSelect struct {
	*BaseSchemaQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bss *BaseSchemaSelect) Aggregate(fns ...AggregateFunc) *BaseSchemaSelect {
	bss.fns = append(bss.fns, fns...)
	return bss
}

// Scan applies the selector query and scans the result into the given value.
func (bss *BaseSchemaSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bss.ctx, "Select")
	if err := bss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BaseSchemaQuery, *BaseSchemaSelect](ctx, bss.BaseSchemaQuery, bss, bss.inters, v)
}

func (bss *BaseSchemaSelect) sqlScan(ctx context.Context, root *BaseSchemaQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bss.fns))
	for _, fn := range bss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
