// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ai-gallery/ent/baseschema"
	"ai-gallery/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BaseSchemaDelete is the builder for deleting a BaseSchema entity.
type BaseSchemaDelete struct {
	config
	hooks    []Hook
	mutation *BaseSchemaMutation
}

// Where appends a list predicates to the BaseSchemaDelete builder.
func (bsd *BaseSchemaDelete) Where(ps ...predicate.BaseSchema) *BaseSchemaDelete {
	bsd.mutation.Where(ps...)
	return bsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (bsd *BaseSchemaDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, bsd.sqlExec, bsd.mutation, bsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (bsd *BaseSchemaDelete) ExecX(ctx context.Context) int {
	n, err := bsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (bsd *BaseSchemaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(baseschema.Table, sqlgraph.NewFieldSpec(baseschema.FieldID, field.TypeInt))
	if ps := bsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, bsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	bsd.mutation.done = true
	return affected, err
}

// BaseSchemaDeleteOne is the builder for deleting a single BaseSchema entity.
type BaseSchemaDeleteOne struct {
	bsd *BaseSchemaDelete
}

// Where appends a list predicates to the BaseSchemaDelete builder.
func (bsdo *BaseSchemaDeleteOne) Where(ps ...predicate.BaseSchema) *BaseSchemaDeleteOne {
	bsdo.bsd.mutation.Where(ps...)
	return bsdo
}

// Exec executes the deletion query.
func (bsdo *BaseSchemaDeleteOne) Exec(ctx context.Context) error {
	n, err := bsdo.bsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{baseschema.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (bsdo *BaseSchemaDeleteOne) ExecX(ctx context.Context) {
	if err := bsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
