// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ai-gallery/ent/account"
	"ai-gallery/ent/baseschema"
	"ai-gallery/ent/schema"
	"ai-gallery/ent/setting"
	"ai-gallery/ent/task"
	"ai-gallery/ent/taskdetail"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountMixin := schema.Account{}.Mixin()
	accountMixinFields0 := accountMixin[0].Fields()
	_ = accountMixinFields0
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescCreateTime is the schema descriptor for create_time field.
	accountDescCreateTime := accountMixinFields0[0].Descriptor()
	// account.DefaultCreateTime holds the default value on creation for the create_time field.
	account.DefaultCreateTime = accountDescCreateTime.Default.(func() time.Time)
	// accountDescUpdateTime is the schema descriptor for update_time field.
	accountDescUpdateTime := accountMixinFields0[1].Descriptor()
	// account.DefaultUpdateTime holds the default value on creation for the update_time field.
	account.DefaultUpdateTime = accountDescUpdateTime.Default.(func() time.Time)
	// account.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	account.UpdateDefaultUpdateTime = accountDescUpdateTime.UpdateDefault.(func() time.Time)
	// accountDescUsername is the schema descriptor for username field.
	accountDescUsername := accountFields[0].Descriptor()
	// account.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	account.UsernameValidator = accountDescUsername.Validators[0].(func(string) error)
	// accountDescPassword is the schema descriptor for password field.
	accountDescPassword := accountFields[1].Descriptor()
	// account.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	account.PasswordValidator = accountDescPassword.Validators[0].(func(string) error)
	// accountDescNickname is the schema descriptor for nickname field.
	accountDescNickname := accountFields[2].Descriptor()
	// account.NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	account.NicknameValidator = accountDescNickname.Validators[0].(func(string) error)
	// accountDescRole is the schema descriptor for role field.
	accountDescRole := accountFields[3].Descriptor()
	// account.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	account.RoleValidator = accountDescRole.Validators[0].(func(string) error)
	baseschemaMixin := schema.BaseSchema{}.Mixin()
	baseschemaMixinFields0 := baseschemaMixin[0].Fields()
	_ = baseschemaMixinFields0
	baseschemaFields := schema.BaseSchema{}.Fields()
	_ = baseschemaFields
	// baseschemaDescCreateTime is the schema descriptor for create_time field.
	baseschemaDescCreateTime := baseschemaMixinFields0[0].Descriptor()
	// baseschema.DefaultCreateTime holds the default value on creation for the create_time field.
	baseschema.DefaultCreateTime = baseschemaDescCreateTime.Default.(func() time.Time)
	// baseschemaDescUpdateTime is the schema descriptor for update_time field.
	baseschemaDescUpdateTime := baseschemaMixinFields0[1].Descriptor()
	// baseschema.DefaultUpdateTime holds the default value on creation for the update_time field.
	baseschema.DefaultUpdateTime = baseschemaDescUpdateTime.Default.(func() time.Time)
	// baseschema.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	baseschema.UpdateDefaultUpdateTime = baseschemaDescUpdateTime.UpdateDefault.(func() time.Time)
	settingMixin := schema.Setting{}.Mixin()
	settingMixinFields0 := settingMixin[0].Fields()
	_ = settingMixinFields0
	settingFields := schema.Setting{}.Fields()
	_ = settingFields
	// settingDescCreateTime is the schema descriptor for create_time field.
	settingDescCreateTime := settingMixinFields0[0].Descriptor()
	// setting.DefaultCreateTime holds the default value on creation for the create_time field.
	setting.DefaultCreateTime = settingDescCreateTime.Default.(func() time.Time)
	// settingDescUpdateTime is the schema descriptor for update_time field.
	settingDescUpdateTime := settingMixinFields0[1].Descriptor()
	// setting.DefaultUpdateTime holds the default value on creation for the update_time field.
	setting.DefaultUpdateTime = settingDescUpdateTime.Default.(func() time.Time)
	// setting.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	setting.UpdateDefaultUpdateTime = settingDescUpdateTime.UpdateDefault.(func() time.Time)
	// settingDescConfigKey is the schema descriptor for config_key field.
	settingDescConfigKey := settingFields[0].Descriptor()
	// setting.ConfigKeyValidator is a validator for the "config_key" field. It is called by the builders before save.
	setting.ConfigKeyValidator = settingDescConfigKey.Validators[0].(func(string) error)
	// settingDescConfigValue is the schema descriptor for config_value field.
	settingDescConfigValue := settingFields[1].Descriptor()
	// setting.ConfigValueValidator is a validator for the "config_value" field. It is called by the builders before save.
	setting.ConfigValueValidator = settingDescConfigValue.Validators[0].(func(string) error)
	// settingDescMark is the schema descriptor for mark field.
	settingDescMark := settingFields[2].Descriptor()
	// setting.MarkValidator is a validator for the "mark" field. It is called by the builders before save.
	setting.MarkValidator = settingDescMark.Validators[0].(func(string) error)
	// settingDescOperateName is the schema descriptor for operate_name field.
	settingDescOperateName := settingFields[4].Descriptor()
	// setting.OperateNameValidator is a validator for the "operate_name" field. It is called by the builders before save.
	setting.OperateNameValidator = settingDescOperateName.Validators[0].(func(string) error)
	taskMixin := schema.Task{}.Mixin()
	taskMixinFields0 := taskMixin[0].Fields()
	_ = taskMixinFields0
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescCreateTime is the schema descriptor for create_time field.
	taskDescCreateTime := taskMixinFields0[0].Descriptor()
	// task.DefaultCreateTime holds the default value on creation for the create_time field.
	task.DefaultCreateTime = taskDescCreateTime.Default.(func() time.Time)
	// taskDescUpdateTime is the schema descriptor for update_time field.
	taskDescUpdateTime := taskMixinFields0[1].Descriptor()
	// task.DefaultUpdateTime holds the default value on creation for the update_time field.
	task.DefaultUpdateTime = taskDescUpdateTime.Default.(func() time.Time)
	// task.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	task.UpdateDefaultUpdateTime = taskDescUpdateTime.UpdateDefault.(func() time.Time)
	// taskDescCategory is the schema descriptor for category field.
	taskDescCategory := taskFields[2].Descriptor()
	// task.CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	task.CategoryValidator = taskDescCategory.Validators[0].(func(string) error)
	// taskDescImgSize is the schema descriptor for img_size field.
	taskDescImgSize := taskFields[5].Descriptor()
	// task.ImgSizeValidator is a validator for the "img_size" field. It is called by the builders before save.
	task.ImgSizeValidator = taskDescImgSize.Validators[0].(func(string) error)
	// taskDescSeed is the schema descriptor for seed field.
	taskDescSeed := taskFields[6].Descriptor()
	// task.SeedValidator is a validator for the "seed" field. It is called by the builders before save.
	task.SeedValidator = taskDescSeed.Validators[0].(func(string) error)
	// taskDescSamplerName is the schema descriptor for sampler_name field.
	taskDescSamplerName := taskFields[7].Descriptor()
	// task.SamplerNameValidator is a validator for the "sampler_name" field. It is called by the builders before save.
	task.SamplerNameValidator = taskDescSamplerName.Validators[0].(func(string) error)
	// taskDescSdModelName is the schema descriptor for sd_model_name field.
	taskDescSdModelName := taskFields[12].Descriptor()
	// task.SdModelNameValidator is a validator for the "sd_model_name" field. It is called by the builders before save.
	task.SdModelNameValidator = taskDescSdModelName.Validators[0].(func(string) error)
	// taskDescSdModelHash is the schema descriptor for sd_model_hash field.
	taskDescSdModelHash := taskFields[13].Descriptor()
	// task.SdModelHashValidator is a validator for the "sd_model_hash" field. It is called by the builders before save.
	task.SdModelHashValidator = taskDescSdModelHash.Validators[0].(func(string) error)
	// taskDescSdVaeName is the schema descriptor for sd_vae_name field.
	taskDescSdVaeName := taskFields[14].Descriptor()
	// task.SdVaeNameValidator is a validator for the "sd_vae_name" field. It is called by the builders before save.
	task.SdVaeNameValidator = taskDescSdVaeName.Validators[0].(func(string) error)
	// taskDescSdVaeHash is the schema descriptor for sd_vae_hash field.
	taskDescSdVaeHash := taskFields[15].Descriptor()
	// task.SdVaeHashValidator is a validator for the "sd_vae_hash" field. It is called by the builders before save.
	task.SdVaeHashValidator = taskDescSdVaeHash.Validators[0].(func(string) error)
	// taskDescVersion is the schema descriptor for version field.
	taskDescVersion := taskFields[17].Descriptor()
	// task.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	task.VersionValidator = taskDescVersion.Validators[0].(func(string) error)
	// taskDescGridImageURL is the schema descriptor for grid_image_url field.
	taskDescGridImageURL := taskFields[18].Descriptor()
	// task.GridImageURLValidator is a validator for the "grid_image_url" field. It is called by the builders before save.
	task.GridImageURLValidator = taskDescGridImageURL.Validators[0].(func(string) error)
	// taskDescStatus is the schema descriptor for status field.
	taskDescStatus := taskFields[19].Descriptor()
	// task.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	task.StatusValidator = taskDescStatus.Validators[0].(func(string) error)
	// taskDescAuthorName is the schema descriptor for author_name field.
	taskDescAuthorName := taskFields[21].Descriptor()
	// task.AuthorNameValidator is a validator for the "author_name" field. It is called by the builders before save.
	task.AuthorNameValidator = taskDescAuthorName.Validators[0].(func(string) error)
	taskdetailMixin := schema.TaskDetail{}.Mixin()
	taskdetailMixinFields0 := taskdetailMixin[0].Fields()
	_ = taskdetailMixinFields0
	taskdetailFields := schema.TaskDetail{}.Fields()
	_ = taskdetailFields
	// taskdetailDescCreateTime is the schema descriptor for create_time field.
	taskdetailDescCreateTime := taskdetailMixinFields0[0].Descriptor()
	// taskdetail.DefaultCreateTime holds the default value on creation for the create_time field.
	taskdetail.DefaultCreateTime = taskdetailDescCreateTime.Default.(func() time.Time)
	// taskdetailDescUpdateTime is the schema descriptor for update_time field.
	taskdetailDescUpdateTime := taskdetailMixinFields0[1].Descriptor()
	// taskdetail.DefaultUpdateTime holds the default value on creation for the update_time field.
	taskdetail.DefaultUpdateTime = taskdetailDescUpdateTime.Default.(func() time.Time)
	// taskdetail.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	taskdetail.UpdateDefaultUpdateTime = taskdetailDescUpdateTime.UpdateDefault.(func() time.Time)
	// taskdetailDescImageURL is the schema descriptor for image_url field.
	taskdetailDescImageURL := taskdetailFields[1].Descriptor()
	// taskdetail.ImageURLValidator is a validator for the "image_url" field. It is called by the builders before save.
	taskdetail.ImageURLValidator = taskdetailDescImageURL.Validators[0].(func(string) error)
}
