// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ai-gallery/ent/predicate"
	"ai-gallery/ent/taskdetail"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskDetailDelete is the builder for deleting a TaskDetail entity.
type TaskDetailDelete struct {
	config
	hooks    []Hook
	mutation *TaskDetailMutation
}

// Where appends a list predicates to the TaskDetailDelete builder.
func (tdd *TaskDetailDelete) Where(ps ...predicate.TaskDetail) *TaskDetailDelete {
	tdd.mutation.Where(ps...)
	return tdd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tdd *TaskDetailDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tdd.sqlExec, tdd.mutation, tdd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tdd *TaskDetailDelete) ExecX(ctx context.Context) int {
	n, err := tdd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tdd *TaskDetailDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(taskdetail.Table, sqlgraph.NewFieldSpec(taskdetail.FieldID, field.TypeInt))
	if ps := tdd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tdd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tdd.mutation.done = true
	return affected, err
}

// TaskDetailDeleteOne is the builder for deleting a single TaskDetail entity.
type TaskDetailDeleteOne struct {
	tdd *TaskDetailDelete
}

// Where appends a list predicates to the TaskDetailDelete builder.
func (tddo *TaskDetailDeleteOne) Where(ps ...predicate.TaskDetail) *TaskDetailDeleteOne {
	tddo.tdd.mutation.Where(ps...)
	return tddo
}

// Exec executes the deletion query.
func (tddo *TaskDetailDeleteOne) Exec(ctx context.Context) error {
	n, err := tddo.tdd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{taskdetail.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tddo *TaskDetailDeleteOne) ExecX(ctx context.Context) {
	if err := tddo.Exec(ctx); err != nil {
		panic(err)
	}
}
