// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// BaseSchema is the predicate function for baseschema builders.
type BaseSchema func(*sql.Selector)

// Setting is the predicate function for setting builders.
type Setting func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// TaskDetail is the predicate function for taskdetail builders.
type TaskDetail func(*sql.Selector)
